<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/Assets/favicon.ico">

    <title><?php echo \Black\Config::get('application')->website->title; ?></title>

    <!-- Bootstrap core CSS -->
    <link href="/Assets/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/Assets/css/application.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <?php
     echo $this->partial('menu.phtml');
     echo $TEMPLATE_CONTENT;
    ?>
    <hr>

      <footer>
        <p><?php echo \Black\Config::get('application')->website->footerFrontLegend; ?></p>
      </footer>
    </div> <!-- /container -->



    <script src="/Assets/bootstrap-3.2.0/js/bootstrap.min.js"></script>
    <script src="/Assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>
