<?php echo $this->partial('head.phtml'); ?>

  <body>

<?php /* include 'menu.phtml'; */ ?>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
<?php
$flashMessages = \Black\View\FlashMessage::getSuccessMessages();
if (is_array($flashMessages)) {
  foreach ($flashMessages as $message) {
    echo "<p class='bg-success text-success'>{$message}</p>";
  }
}

$flashMessages = \Black\View\FlashMessage::getErrorMessages();
if (is_array($flashMessages)) {
  foreach ($flashMessages as $message) {
    echo "<p class='bg-danger text-danger'>{$message}</p>";
  }
}
?>

        <?php echo $TEMPLATE_CONTENT; ?>
        </div>
      </div>


      <hr>

      <footer>
        <p><?php echo \Black\Config::get('application')->website->footerAdminLegend; ?></p>
      </footer>
    </div> <!-- /container -->

  </body>
</html>
