<div class="navbar navbar navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><?php echo \Black\Config::get('application')->website->brand; ?></a>
    </div>

    <div class="navbar-collapse collapse">
<?php
$user = \Black\Container::get('userSession');
if ($user->isLoggedIn): ?>

<ul class="nav navbar-nav navbar-right">
  <!-- <li><a href="#">Link</a></li> -->
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $user->name; ?> <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><a href="/user/dashboard">Dashboard</a></li>
      <li class="divider"></li>
      <li><a href="/user/logout">Logout</a></li>
    </ul>
  </li>
</ul>

<?php else: ?>
      <form class="navbar-form navbar-right" action="/user/login" method="post" role="form">
        <div class="form-group">
          <input type="text" name="email" placeholder="Email" class="form-control">
        </div>
        <div class="form-group">
          <input type="password" name="password"  placeholder="Password" class="form-control">
        </div>
        <input type="hidden" name="signature[csrfHash]" value="<?php echo sha1(session_id()); ?>">
        <button type="submit" class="btn btn-success">Sign in</button>
        <a href="<?php echo $this->url('userRegistration'); ?>" class="btn btn-primary" role="button"><?php echo $this->translate('register'); ?></a>
      </form>
<?php endif; ?>
    </div><!--/.navbar-collapse -->
  </div>
</div>
