<ul class="nav nav-tabs" role="tablist">
  <li <?php if ($selectedTab === 'dashboard') { echo ' class="active"'; } ?>>
    <a href="/user/dashboard">Panel</a></li>
  <li <?php if ($selectedTab === 'profile') { echo ' class="active"'; } ?>>
    <a href="/user/profile">Perfil</a></li>
  <li <?php if ($selectedTab === 'password') { echo ' class="active"'; } ?>>
    <a href="/user/password">Contraseña</a></li>
</ul>
<br><br>
