<div class="form-group">
    <label for="<?php echo $elementId; ?>"><?php echo $labelText; ?></label>
    <input
        type="<?php echo $elementType; ?>"
        name="<?php echo $elementName; ?>"
        class="form-control <?php echo $elementClass; ?>"
        id="<?php echo $elementId; ?>"
        placeholder="<?php echo $elementPlaceHolder; ?>"
        value="<?php echo $elementValue; ?>"
    >
</div>
