<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php echo \Black\Config::get('application')->website->title; ?></title>


    <link rel="icon" href="/Assets/favicon.ico">

    <link href="/Assets/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="/Assets/css/admin.css" rel="stylesheet">

    <?php
    if (!empty($this->styles)) {
        foreach ($this->styles as $css) {
          echo "    <link href='{$css}' rel='stylesheet' type='text/css'>\n";
        }
    }
    ?>

    <?php
    if (!empty($this->javascripts)) {
        foreach ($this->javascripts as $js) {
          echo "<script type='text/javascript' src='{$js}'></script>\n";
        }
    }
    ?>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="/Assets/bootstrap-3.2.0/js/bootstrap.min.js"></script>

    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
