
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
<?php
/*
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
*/
?>
          <a class="navbar-brand" href="/admin">Dashboard</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
                <a href="/" target="_blank">
                    <span class="glyphicon glyphicon-eye-open"></span> Ver el sitio
                </a>
            </li>
            <li>
                <a href="/admin/entity/News" role="button">
                    <span class="glyphicon glyphicon-pencil"></span> Noticias
                </a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Componentes <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
<?php
if (!empty($entitesMenu)):
foreach ($entitesMenu as $entityName => $displayAs):
    echo "<li><a href='/admin/entity/{$entityName}'>{$displayAs}</a></li>";
endforeach;
endif;
?>

              </ul>
            </li>
          </ul>
<?php
/*
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>

          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
*/

?>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/admin/logout">Desconectarse</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
