<div class="form-group">
    <label for="<?php echo $data['id']; ?>"><?php echo $data['label']; ?></label>
    <input
        type="<?php echo $data['type']; ?>"
        name="<?php echo $data['name']; ?>"
        class="form-control <?php echo $data['class']; ?>"
        id="<?php echo $data['id']; ?>"
        placeholder="<?php echo $data['placeholder']; ?>"
        value="<?php echo $data['value']; ?>"
    >
</div>
