
<div class="form-group">
    <label for="<?php echo $data['id']; ?>"><?php echo $data['label']; ?></label>
    <textarea
        id="<?php echo $data['id']; ?>"
        name="<?php echo $data['name']; ?>"
        class="form-control <?php echo $data['class']; ?>"
        rows="<?php echo $data['rows']; ?>"
        placeholder="<?php echo $data['placeholder']; ?>"
    ><?php echo $data['value']; ?></textarea>
</div>
