<div class="bk-box-title">
    <h4><?php echo $currentSection; ?></h4>
</div>

<div class="row">
<?php
if (!empty($sectionArticles)):
  echo '<div class="col-md-8">';
  foreach ($sectionArticles as $key => $article):
echo <<<HTML
    <div class="box-listado border-bottom">
      <h2 class="titulo-h"><a href="/article/{$article->id}">{$article->title}</a></h2>
        <div class="col-md-4 img-listado">
             <a href="/article/{$article->id}"><img src="{$article->image}" style="height: 162px; width: 260px;" alt="" class="img-responsive"/></a>
        </div><!--img-listado-->
      <div class="col-md-8 box-listado">
         <p>{$article->intro}</p>
      </div><!-- col-md-8 box-listado -->
      <hr>
    </div>

HTML;

  endforeach;
  echo '</div>';
endif;
?>


<?php
if (!empty($sectionArticlesRightColumn)):
  echo '<div class="col-md-4 box-left">';
  foreach ($sectionArticlesRightColumn as $key => $article):
echo <<<HTML
    <div class="box-news">
      <h2 class="titulo-h"><a href="/article/{$article->id}">{$article->title}</a></h2>

      <a href="/article/{$article->id}"><img src="{$article->image}" style="max-height: 200px; width: 300px;" class="img-responsive thumb-responsive"></a>

      <p>{$article->intro}</p>
      <br>
      <hr>
    </div><!--/box-news-->


HTML;

  endforeach;
  echo '</div>';
endif;
?>

</div><!-- .row -->

