<br>
<div class="container">
<?php echo $this->partial('tabs-menu.phtml'); ?>
    <div class="row">
        <div class="col-md-3">
          <span class="glyphicon glyphicon-briefcase" style="font-size: 65px;"></span>
          <br>
          <p><a href="/news/new"><?php echo $this->translate('news.new'); ?></a></p>
      </div>

      <div class="col-md-3">
          <span class="glyphicon glyphicon-briefcase" style="font-size: 65px;"></span>
          <br>
          <p><a href="/news/browse"><?php echo $this->translate('news.browse'); ?></a></p>
      </div>
    </div>

</div>



